### PR TITLE
Added Sticky and Normal Pistons

### PR DESCRIPTION
**Pull request by CrazyWolf23**
Just say merge

### CODE REVIEW

**Comment by RandomAltThing** [comment]
Wait.. @jv110 . Pistons and sticky pistons are 2 seperate tiles, aren't they? They were in PocketPower anyway. I will let you have a look at this. We also should have a C++ version of TravisCI

**Comment by RandomAltThing** [comment]
Also, do you have git on PC or SGit on android so you can commit easier?

**Comment by jv110** [comment]
You should really correct the code

**Comment by jv110** [comment]
@RandomAltThing Yes, but both are BlockPistonBases on PC. And I have the GitHub app on PC and PocketGit on my phone.

**Comment by RandomAltThing** [comment]
@jv110 I was talking to crazycard about the git

**Comment by jv110** [comment]
@RandomAltThing oh, you should mention him then :P

**Comment by RandomAltThing** [comment]
@jv110 I couldn't remember his name and cba to scroll up
<hint>github.com/RandomAltThing/Mineserver</hint>

**Comment by CrazyWolf23** [comment]
Dudes I don't understand what I did wrong this time?

**Comment by RandomAltThing** [comment]
@Crazywolf23 Nothing

**Comment by CrazyWolf23** [comment]
@RandomAltThing oh Yay! XD , So should we push?

**Comment by RandomAltThing** [comment]
Idk btw how do we port renders from PC?
I may make a commit with this and some more things.

**Comment by CrazyWolf23** [comment]
@RandomAltThing so merge?

**Comment by CrazyWolf23** [comment]
Yay

**Pull request merged**
